### ISSUE TITLE
Validate matchers

### ISSUE THREAD

**Issue by sbruno** [bochaco/pact-mock-reactive#5]
Matchers are being stored when interactions are registered and saved with the generated pacts but we should validate that they are correct.
We should check that the actual value matches what the matcher says (regex, type, etc).
I'm not sure if this should be done at interaction registration or at pact verification.
I think that ruby implementation does it at registration.

**Comment by bochaco** [comment]
I just committed some changes (e1da86f42466cf370195a18e8eb04abfdd77752e and c95f4eb66fc1f0fd9b7934861e1d56b50454d555) to support this at registration time. The following validations are made for each field within the "responseMatchingRules" object:
- It makes sure that the referenced attribute exists in the response object.
- If the matching rule is a regex, it then verifies that the regex of the rule matches the value registered in the response.

**Comment by sbruno** [comment]
Looks good! I have just tried it and worked as expected.
Thanks!
